In [75]:
import numpy as np
x = np.array([-1.6])
for j in range(100):
    f_xj = x[j] * np.sin(3 * x[j]) - np.exp(x[j])
    f_der_xj = np.sin(3 * x[j]) + 3 * x[j] * np.cos(3 * x[j]) - np.exp(x[j])
    x_new = x[j] - f_xj / f_der_xj
    x = np.append(x, x_new)
    fc=x[j]*np.sin(3*x[j])-np.exp(x[j])
    if abs(fc) < 1e-6:
        break 
print(x)

[-1.6         3.19799514  2.46440244  1.2035359   0.65020146 -0.11692334
 -0.66052349 -0.52192654 -0.56655274 -0.57074658 -0.57078962 -0.57078962]


In [7]:
np.save('A1.npy', x)

In [8]:
np.load('A1.npy')

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962])

In [63]:
xr = -0.4
xl = -0.7
mid = np.array([])

for j in range(100):
    xc = (xr + xl)/2
    mid = np.append(mid, xc) 
    fc = (xc) * np.sin(3*(xc)) - np.exp(xc)
    if ( fc > 0 ):
        xl = xc
    else:
        xr = xc
    if  abs(fc) < 1e-6:
        display(xc); display(j)
        break

-0.5707893371582031

16

In [64]:
print(mid)

[-0.55       -0.625      -0.5875     -0.56875    -0.578125   -0.5734375
 -0.57109375 -0.56992188 -0.57050781 -0.57080078 -0.5706543  -0.57072754
 -0.57076416 -0.57078247 -0.57079163 -0.57078705 -0.57078934]


In [81]:
np.save('A2.npy', mid)

In [82]:
A3 = np.array([x.size, mid.size])
print(A3)
np.save('A3.npy', A3)

[12 17]


In [94]:
A = np.array([[1, 2] , [-1, 1]])
B = np.array([[2, 0] , [0, 2]])
A4 = A + B
print(A4)
np.save('A4.npy', A4)

[[ 3  2]
 [-1  3]]


In [95]:
np.load('A4.npy')

array([[ 3,  2],
       [-1,  3]])

In [96]:
x = np.array([[1],[0]])
y = np.array([[0],[1]])
A5 = 3*x - 4*y
print(A5)
np.save('A5.npy', A5)


[[ 3]
 [-4]]


In [97]:
A6 = A@x
print(A6)
np.save('A6.npy', A6)

[[ 1]
 [-1]]


In [98]:
A7 = B@(x-y)
print(A7)
np.save('A7.npy', A7)

[[ 2]
 [-2]]


In [99]:
D = np.array([[1,2],[2,3],[-1,0]])
A8 = D@x
print(A8)
np.save('A8.npy', A8)

[[ 1]
 [ 2]
 [-1]]


In [100]:
z = np.array([[1],[2],[-1]])
A9 = D@x+z
print(A9)
np.save('A9.npy', A9)

[[ 2]
 [ 4]
 [-2]]


In [101]:
A10 = A@B
print(A10)
np.save('A10.npy', A10)

[[ 2  4]
 [-2  2]]


In [102]:
C = np.array([[2,0,-3],[0,0,-1]])
A11 = B @ C
print(A11)
np.save('A11.npy', A11)

[[ 4  0 -6]
 [ 0  0 -2]]


In [103]:
A12 = C @ D
print(A12)
np.save('A12.npy', A12)

[[5 4]
 [1 0]]
